### ISSUE TITLE
Creating pull requests to rjeczalik

### ISSUE THREAD

**Issue by imsodin** [Zillode/notify#4]
There was just some PR activity over on rjeczalik repo, so there is activity. I would like to create a PR for the changes introduced in #2 and also a work-in-progress PR for #3.
It makes sense that this PRs come from the Zillode fork and not mine. Now this is the first time I have push access to a git repo, so I wanted to ask first: Is it ok if I create the necessary branches and issue the PRs?

**Comment by Zillode** [comment]
Certainly,
