### ISSUE TITLE
weird test failure on aarch64/arm64, epoll_wait not available?

### ISSUE THREAD

**Issue by decathorpe** [Zillode/notify#8]
I'm trying to create a proper fedora package of this go library, but I am hitting this strange error when running the tests on aarch64/arm64:

```
+ go test -compiler gc -ldflags '' github.com/zillode/notify
panic: notify: epoll_wait(2) error function not implemented
goroutine 10 [running]:
github.com/zillode/notify.(*inotify).loop(0x442011c000, 0x442008b7a0)
	(...)/src/github.com/zillode/notify/watcher_inotify.go:215 +0x114
created by github.com/zillode/notify.(*inotify).lazyinit
	(...)/src/github.com/zillode/notify/watcher_inotify.go:133 +0x10c
FAIL	github.com/zillode/notify	1.774s
```

It seems this issue has already been fixed upstream: https://github.com/rjeczalik/notify/pull/116

**Comment by imsodin** [comment]
I just merged upstream. Can you report back whether it fixed your issue - thanks.

**Comment by decathorpe** [comment]
Yes, tests now pass on all of fedora's primary architectures! Thanks for fixing this so quickly.
